language: python
python:
  - 2.7

env:
  - CFLAGS=-I/usr/include/gdal

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get -qq update
  - sudo apt-get -y install libgdal-dev libgdal1h gdal-bin

install: 
  - pip install GDAL==1.10.0
  - pip install -r requirements.txt
  - pip install coveralls

script: coverage run --source=spillway setup.py test
after_success: coveralls
